/**
 * Readable, git-ignored copies of src/levels.res under tools/tune/results, for reading and
 * diffing by eye: the tuned numbers, the proof designs, the full results, the difficulty and a
 * report. They are only ever written, never read back; `npm run tune:unpack` regenerates them.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { levelCode } from '../../src/chapters';
import { BASE_LEVELS, type BonusGoal } from '../../src/levels';
import { PEAK_CAP } from './difficulty';
import { designsOf } from './levelres.mjs';
import type { LevelResource } from './types';

export const RESULTS_DIR = fileURLToPath(new URL('./results', import.meta.url));

export function writeReadable(res: LevelResource): void {
  mkdirSync(RESULTS_DIR, { recursive: true });
  const write = (name: string, value: unknown) => writeFileSync(`${RESULTS_DIR}/${name}`, `${JSON.stringify(value, null, 1)}\n`);
  write('tuned.json', { levels: res.levels });
  write('designs.json', designsOf(res));
  write('state.json', res.results);
  write('difficulty.json', res.difficulty);
  writeFileSync(`${RESULTS_DIR}/report.md`, report(res));
}

export function report(res: LevelResource): string {
  const rows = BASE_LEVELS.map((b) => {
    const r = res.results[b.id];
    if (!r) return `| ${levelCode(b.id)} | ${b.name} | not tuned | | | | | | |`;
    const req = r.requires.map((q) => `${q.ok ? '✓' : '✗'} ${q.mat}`).join(', ');
    const cuts = r.shortcuts.map((s) => (s.ok ? '✓' : '✗')).join('');
    const roomText = r.room ? `${r.room.pass}/${r.room.total}` : '';
    const params = Object.keys(r.params).length ? JSON.stringify(r.params) : '';
    return `| ${levelCode(b.id)} | ${b.name} | ${r.ok ? ['✓', ...(r.warnings ?? [])].join(' ') : `✗ ${r.notes.join('; ')}`} | ${usd(r.reference.cost)} (${pct(r.reference.peak)}) | ${r.seed ? usd(r.seed.cost) : ''} | ${usd(r.target)} | ${usd(r.money)} | ${bonusText(r.bonus)} | ${[req, cuts && `shortcuts ${cuts}`, roomText && `room ${roomText}`, params].filter(Boolean).join('; ')} |`;
  });
  return [
    '# Level tuning report',
    '',
    'Generated by `npm run tune`. Reference: the cheapest design found that crosses with peak stress at or below',
    `${pct(PEAK_CAP)}. Hand: the hand-made design in src/solutions.ts. Target and budget follow from the reference`,
    'and the difficulty settings.',
    '',
    '| Level | Name | OK | Reference | Hand | Target | Budget | Bonus | Checks |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

export function usd(v: number): string {
  return `$${Math.round(v).toLocaleString('en-US')}`;
}
export function pct(v: number): string {
  return `${Math.round(v * 100)}%`;
}
export function bonusText(b: BonusGoal): string {
  return b.kind === 'without' ? `no ${b.mat}` : b.kind === 'stress' ? `stress < ${pct(b.max)}` : b.kind === 'parts' ? `≤ ${b.max} parts` : `≤ ${usd(b.max)}`;
}
