import type { MaterialId } from './physics/materials';
import type { VehicleId } from './physics/vehicles';
import { levels as tunedLevels } from './levels.res';

export type Pt = [number, number];

/** A slim steel pylon: [x, baseY, topY]. Decks may pass through it; its anchors are listed with the level's. */
export type Tower = [number, number, number];

/** A rock overhang above one approach road, from `bottom` up to `top`, reaching `reach` m over the gap. */
export interface Overhang {
  side: 'left' | 'right';
  bottom: number;
  top: number;
  reach: number;
}

/** An optional extra goal on top of the three stars. Meeting it earns the bonus star. */
export type BonusGoal =
  /** Build for this many dollars or less. */
  | { kind: 'cost'; max: number }
  /** Keep peak stress below this ratio. */
  | { kind: 'stress'; max: number }
  /** Use this many parts or fewer. A split beam counts once. */
  | { kind: 'parts'; max: number }
  /** Build without this material. */
  | { kind: 'without'; mat: MaterialId };

export interface LevelDef {
  id: number;
  name: string;
  tip: string;
  /** Gap between the two banks; the left bank top is at (0, 0). */
  width: number;
  /** Height of the right bank's top edge (defaults to 0, level with the left). */
  rightY?: number;
  anchors: Pt[];
  /**
   * Concrete piers rise from the water to these points. Most are topped by a bolt; one without
   * is a seat, where a deck rests and can lift off.
   */
  piers: Pt[];
  /** Materials offered on this level, in toolbar order. */
  materials: MaterialId[];
  /** Cash available for the whole bridge, in dollars. */
  money: number;
  /** Building for this much or less earns a star. */
  target: number;
  vehicle: VehicleId;
  waterY: number;
  towers?: Tower[];
  /**
   * Steel masts on a hinge at their foot: [x, baseY, topY], with a bolt on top that is not one of
   * the level's anchors, since it tips freely. It only pushes down, so backstays have to hold it.
   */
  masts?: Tower[];
  overhangs?: Overhang[];
  /** Ship channels: [x0, x1, top]. Nothing may be built between x0 and x1 from the water up to `top`. */
  channels?: [number, number, number][];
  bonus: BonusGoal;
  /** Vehicles following the first one across, in order: a convoy. */
  convoy?: VehicleId[];
  /**
   * A tall ship sails through the first channel before traffic may go, with its mast up to
   * this height: the bridge has to open for it, on hydraulic rams, and close again.
   */
  ship?: { mast: number };
  /** Most parts of a material a level allows, on top of the budget. A split beam counts once. */
  limits?: Partial<Record<MaterialId, number>>;
  /** Price of building from an anchor, charged once per anchor used; the two road ends are free. */
  anchorCost?: number;
  /**
   * Concrete anchors on offer: blocks the player sets into either bank, on whole meters from
   * 1 m to `reach` m back from the edge, at a price each. See BLOCK in materials.
   */
  blocks?: { reach: number };
  /** Scene for the test drive, by theme id. Built-in levels use their chapter's; custom levels pick one. */
  theme?: string;
  /**
   * Ghost members drawn as a hint until the first test, for levels that introduce a mechanic.
   * A deck ghost may span a whole road run, and a ghost that ends partway along another shows
   * where that beam gets split.
   */
  hint?: [Pt, Pt, MaterialId][];
  /** The hint is a whole working bridge, not just a new mechanic: TEST pulses once it is built. */
  hintSolves?: boolean;
}

/** What the level optimizer (tools/tune) decides: the money, and any geometry it was allowed to adjust. */
export type Tuned = Pick<LevelDef, 'money' | 'target' | 'bonus'> & { geometry?: Partial<Pick<LevelDef, GeometryKey>> };

/** Level fields the optimizer may adjust when a level marks them as tunable. */
export type GeometryKey = 'width' | 'rightY' | 'anchors' | 'piers' | 'waterY' | 'towers' | 'overhangs' | 'channels' | 'hint';

/** A level as authored: everything but the numbers the optimizer tunes. */
export type LevelBase = Omit<LevelDef, 'money' | 'target' | 'bonus'>;

/** The optimizer's output, generated by `npm run tune` and packed into src/levels.res. */
export const TUNED: { levels: Record<string, Tuned & { fingerprint?: string }> } = { levels: tunedLevels };

/** A level with its tuned numbers and geometry applied. */
export function applyTuning(base: LevelBase, t: Tuned): LevelDef {
  return { ...base, ...t.geometry, money: t.money, target: t.target, bonus: t.bonus };
}

export const BASE_LEVELS: LevelBase[] = [
  {
    id: 1,
    name: 'First Crossing',
    tip: 'Drag from a red bolt to lay road. Brace it from below with wood.',
    width: 4,
    anchors: [[0, 0], [4, 0], [0, -2], [4, -2]],
    piers: [],
    materials: ['road', 'wood'],
    vehicle: 'car',
    waterY: -4,
    hint: [
      [[0, 0], [2, 0], 'road'],
      [[2, 0], [4, 0], 'road'],
      [[0, -2], [2, 0], 'wood'],
      [[4, -2], [2, 0], 'wood'],
    ],
    hintSolves: true,
  },
  {
    id: 2,
    name: 'Babbling Brook',
    tip: 'Triangles are rigid. Squares fold.',
    width: 6,
    anchors: [[0, 0], [6, 0], [0, -2], [6, -2]],
    piers: [],
    materials: ['road', 'wood'],
    vehicle: 'car',
    waterY: -4,
  },
  {
    id: 3,
    name: 'Over the Top',
    tip: 'No low anchors here: build your truss above the road.',
    width: 8,
    anchors: [[0, 0], [8, 0]],
    piers: [],
    materials: ['road', 'wood'],
    vehicle: 'car',
    waterY: -5,
  },
  {
    id: 4,
    name: 'Steel Delivery',
    tip: 'Steel is strong and long, but scarce. Spend it where stress runs red.',
    width: 10,
    anchors: [[0, 0], [10, 0], [0, -3], [10, -3]],
    piers: [],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'van',
    waterY: -5,
  },
  {
    id: 5,
    name: 'Uphill Climb',
    tip: 'The far bank is higher. Drag one long road run and the pieces follow the slope.',
    width: 10,
    rightY: 2,
    anchors: [[0, 0], [10, 2], [0, -2], [10, 0]],
    piers: [],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'van',
    waterY: -5,
  },
  {
    id: 6,
    name: 'Stepping Stone',
    tip: 'A pier in the middle halves the span.',
    width: 12,
    anchors: [[0, 0], [12, 0], [6, -3]],
    piers: [[6, -3]],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'van',
    waterY: -6,
  },
  {
    id: 7,
    name: 'Heavy Haul',
    tip: 'A 22 t dump truck. Road carries up to 30 t, but the truss under it has to carry the rest.',
    width: 12,
    anchors: [[0, 0], [12, 0], [0, -2], [12, -2]],
    piers: [],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'truck',
    waterY: -5,
  },
  {
    id: 8,
    name: 'Canyon Run',
    tip: 'Long compression members buckle. Keep them short.',
    width: 14,
    anchors: [[0, 0], [14, 0], [0, -3], [14, -3]],
    piers: [],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'truck',
    waterY: -7,
  },
  {
    id: 9,
    name: 'Down the Gorge',
    tip: 'Downhill run. Steel is plentiful here: brace the low end well.',
    width: 12,
    rightY: -1,
    anchors: [[0, 0], [12, -1], [0, -3], [12, -3]],
    piers: [],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'van',
    waterY: -7,
  },
  {
    id: 10,
    name: 'Twin Towers',
    tip: 'High anchors love steel in tension.',
    width: 14,
    anchors: [[0, 0], [14, 0], [0, 3], [14, 3]],
    piers: [],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'truck',
    waterY: -6,
  },
  {
    id: 11,
    name: 'School Run',
    tip: 'Precious cargo. Keep it green.',
    width: 16,
    anchors: [[0, 0], [16, 0], [8, -3], [0, -2], [16, -2]],
    piers: [[8, -3]],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'bus',
    waterY: -7,
  },
  {
    id: 12,
    name: 'The Grand Span',
    tip: 'Everything you have learned. Good luck, engineer.',
    width: 20,
    anchors: [[0, 0], [20, 0], [6, -3], [14, -3]],
    piers: [[6, -3], [14, -3]],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'bus',
    waterY: -7,
  },
  {
    id: 13,
    name: 'Hanging On',
    tip: 'Cables only pull, never push, and they cost more than wood. Hang the middle; push the ends up from below.',
    width: 14,
    anchors: [[0, 0], [14, 0], [0, 6], [14, 6], [0, -2], [14, -2]],
    piers: [],
    towers: [[0, 0, 6], [14, 0, 6]],
    materials: ['road', 'wood', 'steel', 'cable'],
    vehicle: 'van',
    // Cables have to do the work: too few beams for a truss under the deck.
    limits: { wood: 6, steel: 2 },
    waterY: -6,
    hint: [
      [[0, 0], [14, 0], 'road'],
      [[0, 6], [6, 0], 'cable'],
      [[14, 6], [8, 0], 'cable'],
    ],
  },
  {
    id: 14,
    name: 'Stayed',
    tip: 'Long cables from one pylon get expensive. Hang a few joints and stiffen the deck between them.',
    width: 18,
    anchors: [[0, 0], [18, 0], [9, 7], [0, -2], [18, -2]],
    piers: [],
    towers: [[9, -7, 7]],
    materials: ['road', 'wood', 'steel', 'cable'],
    vehicle: 'van',
    // Cables have to do the work: too few beams for a truss under the deck.
    limits: { wood: 10, steel: 2, cable: 4 },
    waterY: -7,
  },
  {
    id: 15,
    name: 'Cliffhanger',
    tip: 'The middle is out of reach from the cliffs. Cables can meet in mid-air.',
    width: 16,
    anchors: [[0, 0], [16, 0], [1, 9], [15, 9]],
    piers: [],
    overhangs: [
      { side: 'left', bottom: 4, top: 13, reach: 1.2 },
      { side: 'right', bottom: 4, top: 13, reach: 1.2 },
    ],
    materials: ['road', 'wood', 'steel', 'cable'],
    vehicle: 'truck',
    // Cables have to do the work: too few beams for a truss under the deck.
    limits: { wood: 6, steel: 4 },
    waterY: -8,
  },
  {
    id: 16,
    name: 'Mid-span',
    tip: 'Drag from the middle of a beam to add a joint there. Split pieces cost nothing extra.',
    width: 16,
    anchors: [[0, 0], [16, 0], [0, -3], [16, -3]],
    piers: [],
    materials: ['road', 'wood', 'steel', 'cable'],
    vehicle: 'van',
    waterY: -7,
    hint: [
      [[0, 0], [16, 0], 'road'],
      [[0, 0], [2, 2], 'steel'],
      [[2, 2], [6, 2], 'steel'],
      [[4, 0], [4, 2], 'wood'],
    ],
  },
  {
    id: 17,
    name: 'Big Rig',
    tip: 'Forty tonnes of trouble. Heavy deck carries what road cannot.',
    width: 20,
    anchors: [[0, 0], [20, 0], [10, -4], [0, -3], [20, -3]],
    piers: [[10, -4]],
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'semi',
    waterY: -7,
  },
  {
    id: 18,
    name: 'Valley Drop',
    tip: 'One tall pylon, one short one. Cables pull from above; struts push from below.',
    width: 24,
    rightY: -3,
    anchors: [[0, 0], [24, -3], [8, 7], [16, -5], [0, -3], [24, -6]],
    piers: [],
    towers: [[8, -9, 7], [16, -9, -5]],
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'truck',
    // Cables have to do the work: too few beams for a truss under the deck.
    limits: { wood: 6, steel: 6 },
    waterY: -9,
  },
  {
    id: 19,
    name: 'Twin Pylons',
    tip: 'The pylon tops are out of cable reach. String a main cable between them, then drop hangers to the deck.',
    width: 28,
    anchors: [[0, 0], [28, 0], [6, 0], [22, 0], [6, 12], [22, 12], [0, -3], [28, -3]],
    piers: [],
    towers: [[6, -8, 12], [22, -8, 12]],
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'bus',
    // Cables have to do the work: too few beams for a truss under the deck.
    limits: { wood: 12, steel: 6 },
    waterY: -8,
  },
  {
    id: 20,
    name: 'The Long Way',
    tip: 'Thirty-two meters and a school bus. Main cables need sag: a straight cable cannot carry a load.',
    width: 32,
    anchors: [[0, 0], [32, 0], [16, -4], [8, 11], [24, 11], [0, 4], [32, 4], [0, -3], [32, -3]],
    piers: [[16, -4]],
    towers: [[8, -9, 11], [24, -9, 11], [0, 0, 4], [32, 0, 4]],
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'bus',
    // Cables have to do the work: too few beams for a truss under the deck.
    limits: { wood: 6, steel: 4 },
    waterY: -9,
  },
  {
    id: 21,
    name: 'Sawhorse',
    tip: 'A rock in the middle of the stream. Lean on it.',
    width: 8,
    anchors: [[0, 0], [8, 0], [4, -2]],
    piers: [[4, -2]],
    materials: ['road', 'wood'],
    vehicle: 'car',
    waterY: -5,
  },
  {
    id: 22,
    name: 'Two Piers',
    tip: 'Three short spans are easier than one long one.',
    width: 18,
    anchors: [[0, 0], [18, 0], [6, -2], [12, -2], [0, -2], [18, -2]],
    piers: [[6, -2], [12, -2]],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'van',
    waterY: -6,
  },
  {
    id: 23,
    name: 'High Water',
    tip: 'The river is up. There is no room under the deck: build above it.',
    width: 14,
    anchors: [[0, 0], [14, 0]],
    piers: [],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'van',
    waterY: -1.5,
  },
  {
    id: 24,
    name: 'Ferry Lane',
    tip: 'Ships need the channel. Ramp the road up and over, and let the pylons help.',
    width: 24,
    anchors: [[0, 0], [24, 0], [7, 10], [17, 10], [0, -2], [24, -2]],
    piers: [],
    towers: [[7, -2, 10], [17, -2, 10]],
    channels: [[8, 16, 1.5]],
    materials: ['road', 'wood', 'steel', 'cable'],
    vehicle: 'truck',
    waterY: -2,
    hint: [
      [[0, 0], [8, 2], 'road'],
      [[8, 2], [16, 2], 'road'],
      [[16, 2], [24, 0], 'road'],
    ],
  },
  {
    id: 25,
    name: 'Switchback',
    tip: 'A steep climb with a full load. The pier takes half the work.',
    width: 20,
    rightY: 4,
    anchors: [[0, 0], [20, 4], [10, -2], [0, -2], [20, 2]],
    piers: [[10, -2]],
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'truck',
    waterY: -6,
  },
  {
    id: 26,
    name: 'Overpass',
    tip: 'Rock on one side, a pylon on the other. Meet in the middle.',
    width: 22,
    anchors: [[0, 0], [22, 0], [1, 8], [16, 8]],
    piers: [],
    towers: [[16, -8, 8]],
    overhangs: [{ side: 'left', bottom: 4, top: 12, reach: 1.2 }],
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'truck',
    waterY: -8,
  },
  {
    id: 27,
    name: 'Gauntlet',
    tip: 'The piers sit deep. Build trestles up to the deck.',
    width: 26,
    anchors: [[0, 0], [26, 0], [9, -6], [17, -6], [0, -3], [26, -3]],
    piers: [[9, -6], [17, -6]],
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'bus',
    waterY: -8,
  },
  {
    id: 28,
    name: 'Iron Horse',
    tip: 'Twenty-four meters, one pier, one semi truck.',
    width: 24,
    anchors: [[0, 0], [24, 0], [12, -4], [0, -3], [24, -3]],
    piers: [[12, -4]],
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'semi',
    waterY: -7,
  },
  {
    id: 29,
    name: 'Sky Road',
    tip: 'Hang the middle from the pylons. Truss the ends.',
    width: 34,
    anchors: [[0, 0], [34, 0], [8, 0], [26, 0], [8, 12], [26, 12], [0, -3], [34, -3]],
    piers: [],
    towers: [[8, -8, 12], [26, -8, 12]],
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'truck',
    // Cables have to do the work: too few beams for a truss under the deck.
    limits: { wood: 20, steel: 4 },
    waterY: -8,
  },
  {
    id: 30,
    name: 'Magnum Opus',
    tip: 'Thirty-six meters, forty tonnes and a ship channel. Everything you know.',
    width: 36,
    anchors: [[0, 0], [36, 0], [8, 0], [28, 0], [8, 14], [28, 14], [0, -3], [36, -3]],
    piers: [],
    towers: [[8, -8, 14], [28, -8, 14]],
    channels: [[9, 27, 0]],
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'semi',
    waterY: -8,
  },
  {
    id: 31,
    name: 'Bascule',
    tip: 'Trace the ghost: a road hinged at the bank, a wood truss to stiffen it, and a ram on the pier to lift it for the ship.',
    width: 8,
    anchors: [[0, 0], [4, -3]],
    piers: [[4, -3]],
    channels: [[5, 8, 0]],
    ship: { mast: 3 },
    materials: ['road', 'wood', 'steel', 'ram'],
    vehicle: 'car',
    waterY: -5,
    hint: [
      [[0, 0], [8, 0], 'road'],
      [[4, -3], [4, 0], 'ram'],
      [[0, 0], [2, 2], 'wood'],
      [[2, 0], [2, 2], 'wood'],
      [[2, 2], [4, 2], 'wood'],
      [[4, 0], [4, 2], 'wood'],
      [[2, 2], [4, 0], 'wood'],
      [[4, 2], [6, 2], 'wood'],
      [[6, 0], [6, 2], 'wood'],
      [[6, 2], [4, 0], 'wood'],
      [[6, 2], [8, 0], 'wood'],
    ],
    hintSolves: true,
  },
  {
    id: 32,
    name: 'Convoy',
    tip: 'Three vans, nose to tail, all on the bridge at once. Steel is rationed.',
    width: 14,
    anchors: [[0, 0], [14, 0], [7, -3], [0, -2], [14, -2]],
    piers: [[7, -3]],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'van',
    convoy: ['van', 'van'],
    limits: { steel: 6 },
    waterY: -5,
  },
  {
    id: 33,
    name: 'Toll Bridge',
    tip: 'Every bolt off the road costs $1,000 to build from. Choose your piers.',
    width: 20,
    anchors: [[0, 0], [20, 0], [6, -2], [10, -2], [14, -2], [0, -2], [20, -2]],
    piers: [[6, -2], [10, -2], [14, -2]],
    materials: ['road', 'wood', 'steel'],
    vehicle: 'truck',
    anchorCost: 1000,
    waterY: -5,
  },
  {
    id: 34,
    name: 'Harbor Gate',
    tip: 'A fixed span out to the pier, then a leaf that lifts for the ship.',
    width: 16,
    anchors: [[0, 0], [8, 0], [12, -3], [0, -3]],
    piers: [[8, 0], [12, -3]],
    channels: [[13, 16, 0]],
    ship: { mast: 3 },
    materials: ['road', 'wood', 'steel', 'ram'],
    vehicle: 'truck',
    waterY: -5,
  },
  {
    id: 35,
    name: 'Rush Hour',
    tip: 'The ship goes first, then a car, a van and a dump truck. One ram to lift it all.',
    width: 10,
    anchors: [[0, 0], [6, -4], [0, -3]],
    piers: [[6, -4]],
    channels: [[7, 10, 0]],
    ship: { mast: 4 },
    materials: ['road', 'heavy', 'wood', 'steel', 'ram'],
    vehicle: 'car',
    convoy: ['van', 'truck'],
    limits: { ram: 1 },
    waterY: -5,
  },
  {
    id: 36,
    name: 'Deadweight',
    tip: 'The masts only push down. Run a backstay from each mast top to a concrete anchor on the bank, or the main cable pulls them over.',
    width: 16,
    anchors: [[0, 0], [16, 0], [0, -2], [16, -2]],
    piers: [],
    masts: [[3, -5, 8], [13, -5, 8]],
    blocks: { reach: 6 },
    materials: ['road', 'wood', 'cable'],
    vehicle: 'car',
    // A wood truss could carry the car alone; this leaves enough for a strut or two.
    limits: { wood: 4 },
    waterY: -5,
    hint: [
      [[0, 0], [16, 0], 'road'],
      [[3, 8], [4, 6], 'cable'],
      [[4, 6], [6, 4], 'cable'],
      [[6, 4], [8, 3], 'cable'],
      [[8, 3], [10, 4], 'cable'],
      [[10, 4], [12, 6], 'cable'],
      [[12, 6], [13, 8], 'cable'],
      [[4, 6], [4, 0], 'cable'],
      [[6, 4], [6, 0], 'cable'],
      [[8, 3], [8, 0], 'cable'],
      [[10, 4], [10, 0], 'cable'],
      [[12, 6], [12, 0], 'cable'],
      [[3, 8], [2, 0], 'cable'],
      [[13, 8], [14, 0], 'cable'],
      [[3, 8], [0, 4], 'cable'],
      [[0, 4], [-3, 0], 'cable'],
      [[13, 8], [16, 4], 'cable'],
      [[16, 4], [19, 0], 'cable'],
    ],
    hintSolves: true,
  },
  {
    id: 37,
    name: 'Lift-Off',
    tip: 'Tall masts and little room behind them. A steep backstay pulls straight up, and a block only weighs so much.',
    width: 18,
    anchors: [[0, 0], [18, 0], [0, -2], [18, -2]],
    piers: [],
    masts: [[2, -5, 10], [16, -5, 10]],
    blocks: { reach: 4 },
    materials: ['road', 'wood', 'cable'],
    vehicle: 'truck',
    limits: { wood: 4 },
    waterY: -5,
  },
  {
    id: 38,
    name: 'Raise Your Own',
    tip: 'No masts this time. Brace a steel tower on each pair of piers, anchor it back, and hang a stiff heavy deck from it.',
    width: 24,
    anchors: [[0, 0], [24, 0], [2, 0], [4, 0], [20, 0], [22, 0]],
    piers: [[2, 0], [4, 0], [20, 0], [22, 0]],
    blocks: { reach: 6 },
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'bus',
    limits: { wood: 6, steel: 14 },
    waterY: -6,
  },
  {
    id: 39,
    name: 'Side Spans',
    tip: 'The backstays can carry more than the masts: hang the side spans from them too.',
    width: 30,
    anchors: [[0, 0], [30, 0], [0, -3], [30, -3]],
    piers: [],
    masts: [[8, -6, 12], [22, -6, 12]],
    blocks: { reach: 8 },
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'truck',
    limits: { wood: 4, steel: 4 },
    waterY: -6,
  },
  {
    id: 40,
    name: 'Anchorage',
    tip: 'Forty tonnes on a hung deck. One block per side will not hold it.',
    width: 36,
    anchors: [[0, 0], [36, 0], [0, -3], [36, -3]],
    piers: [],
    masts: [[8, -7, 12], [28, -7, 12]],
    blocks: { reach: 10 },
    materials: ['road', 'heavy', 'wood', 'steel', 'cable'],
    vehicle: 'semi',
    limits: { wood: 4, steel: 4 },
    waterY: -7,
  },
];

/** Stand-in numbers for a level the tuner hasn't run on yet: playable, but with no real target. */
export const UNTUNED: Tuned = { money: 100000, target: 0, bonus: { kind: 'stress', max: 0.5 } };

export const LEVELS: LevelDef[] = BASE_LEVELS.map((b) => applyTuning(b, TUNED.levels[b.id] ?? UNTUNED));

export const START_X = -8;

/** Piers with no bolt on top: a deck built on or across one rests on the pier and can lift off it. */
export function seatPiers(level: LevelDef): Pt[] {
  const bolted = (x: number, y: number) => level.anchors.some((a) => Math.abs(a[0] - x) < 1e-6 && Math.abs(a[1] - y) < 1e-6);
  return level.piers.filter(([x, y]) => !bolted(x, y));
}

export function bankY(level: LevelDef): number {
  return level.rightY ?? 0;
}

export function goalX(level: LevelDef): number {
  return level.width + 4;
}
